### PR TITLE
Styling: Checkbox States (Error/Warning/Success)

### LINKED ISSUE #1883: Checkbox - Define state styling (Success/Warning/Error status)
## Objectives
- Apply status styling to checkboxes (Success, Warning, Error)
- Scope of work includes Default and Focus states
- Styling aligns with [text inputs](https://cfpb.github.io/design-system/components/text-inputs)

**Default**
Screenshot 2024-01-22 at 3 39 34 PM

**Focus**
Screenshot 2024-01-22 at 3 39 25 PM

### PR DESCRIPTION
**Pull request by shindigira**
closes #1883

## Changes
- Carried over the error/warning/success state styling from TextInput to Checkboxes
- Updated the Checkbox stories to show the new styling

## How to Test 
- Test Link: https://deploy-preview-1889--cfpb-design-system.netlify.app/
- **Code inspect** `form-fields.less` and ensure no unintended styling changes affect other components
- **Navigate to the `Checkboxes` story section and view the new styles

## Screenshot(s)

Added states

|Before|After|
|---|---|
|Screenshot 2024-01-22 at 12 00 47 PM|Screenshot 2024-01-22 at 12 18 31 PM|

### CODE REVIEW

**Comment by natalia-fitzgerald** [comment]
@shindigira 
Please present to match the Text inputs page. Sections will be "Status" and "Validation status" 
Screenshot 2024-01-22 at 11 42 33 AM

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@shindigira 
I would like to show only the default states for Success, Warning, and Error. 

- Change "Variation status" (h3) to "Validation status" (h4) 
- Show Default state for Success, Warning, Error
- Success should be Green (currently shows the Default checkbox style - Gray)

Screenshot 2024-01-22 at 12 17 59 PM

For text inputs we use outline to accomplish the 1px border. It looks like in this implementation we're using box shadow. Should we be consistent?

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@shindigira 
I show that Text inputs uses outline instead of box shadow. 
Screenshot 2024-01-22 at 1 02 17 PM

It looks like there was an inadvertent change to the "Standard checkbox with helper text" live code example. Instead of "Checkbox label (This is optional helper text)" it is showing "Success". Can you correct? 

In current PR: 
Screenshot 2024-01-22 at 1 05 44 PM

Currently live on page (correct): 
Screenshot 2024-01-22 at 1 05 31 PM

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@shindigira 
Is it possible to define hover+focus? 
- Success: Green
- Warning: Gold
- Error: Red

Currently hover is still Pacific which is what I would expect since we're handling that change separately. But can we define the hover+focus as part of this change?

**Review by natalia-fitzgerald — APPROVED** [review]
@shindigira Nice work! This looks good to me.

**Review by billhimmelsbach — APPROVED** [review]
Great!

**Review by anselmbradford — APPROVED** [review]
LGTM 👍 !

**Pull request merged**
