### PR TITLE
Add heading link styles

### PR DESCRIPTION
**Pull request by alexm118**
[Issue #1069](https://github.com/cfpb/design-system/issues/1069 ) asks for documentation around links that are also heading elements. Our current system does not have a method for styling links with black text so I am adding a new class to apply to links.

## Additions

- `a-link__heading` which colors the link black like an `h4` would be, as well as alters the default hover appearance to mirror what is currently done on cfgov.

## Testing

1. Ran the `a11y` tests.

## Notes

- Not sure if this is the correct process for adding these links

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome on desktop
- [ ] Firefox
- [ ] Safari on macOS
- [ ] Edge
- [ ] Internet Explorer 9, 10, and 11
- [ ] Safari on iOS
- [ ] Chrome on Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by chosak** [comment]
Thanks @alexm118! Could you possibly also add a documentation edit to the [links page](https://cfpb.github.io/design-system/components/links) to demonstrate how this proposed style would look?

**Comment by anselmbradford** [comment]
Is this currently used in the cf.gov codebase somewhere?

**Comment by Scotchester** [comment]
I think this PR misconstrues what the original issue (#1069) wants. As I understand it, the desired change is to add written content to the DS's Links page describing how links within headings are styled.

**Comment by Scotchester** [comment]
Headings that linked, that is. Where the entire text of the heading is a link.

**Pull request closed without merging**
