### PR TITLE
Maintain text input modifier colors on focus/hover

### PR DESCRIPTION
**Pull request by contolini**
The pacific focus state of our text inputs overrides any modification
colors for error/warning/success. This means that if an input field
is modified while the user is actively focused on it, they won't receive
visual feedback that something has changed.

## Additions

- Hover/focus states to text input modifiers.

## Testing

1. Compare the three production [modified text inputs](https://cfpb.github.io/design-system/components/notifications#warning-notification-field-level) to the [PR preview](https://deploy-preview-1257--cfpb-design-system.netlify.app/design-system/components/notifications#warning-notification-field-level). Also compare them to the [default text inputs](https://cfpb.github.io/design-system/components/text-inputs).

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome on desktop
- [ ] Firefox
- [ ] Safari on macOS
- [ ] Edge
- [ ] Internet Explorer 9, 10, and 11
- [ ] Safari on iOS
- [ ] Chrome on Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by contolini** [comment]
TBH I'm not sure I like this change because there's now no visual feedback for hovering... hmmmmmm...

**Comment by niqjohnson** [comment]
@contolini: Yeah, I agree, not having a hover state on fields with errors feels off. What if we brought the pacific hover border back for fields with errors but made sure that the focus state has priority over that, so if you're hovering on a focused field with an error the field will have the error-color border and outline. That's how error-free fields behave, so it'd be consistent, and it would also work for the use case I'm working on where a field needs to show an error state after you type a certain number of characters (so you might be both focused and hovering on the field when it needs to turn into a field with an error).

**Comment by niqjohnson** [comment]
@contolini, what do you think of the commit I just pushed, d039cc5? That brings back regular hover styles to error fields but gives them a focus state that uses the error border color even when you're focused and hovered.

**Comment by contolini** [comment]
@niqjohnson I dig it! Looks good to me.

**Comment by niqjohnson** [comment]
@contolini, awesome. I feel like I probably shouldn't approve the PR now that I worked on it. Up to @anselmbradford?

**Review by anselmbradford — APPROVED** [review]
We might want to make a [mixin](https://lesscss.org/features/#mixins-feature) in this less file that takes a color and spits out these generated patterns. Feel free to do that if you think it's a good idea.

**Comment by contolini** [comment]
Thanks @anselmbradford and @niqjohnson! I agree that a mixin makes sense but I'm going to skip it because I'm short on time nowadays and the Less will transpile to the same amount of CSS with or without the mixin so I can sleep guilt-free.

**Pull request merged**
