### PR TITLE
Convert packages to ESM modules

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes https://github.com/cfpb/design-system/issues/1495

## Changes

- Convert packages to ESM modules

## Testing

1. PR checks should pass.

### CODE REVIEW

**Comment by anselmbradford** [comment]
More work to do to update the tests

**Comment by anselmbradford** [comment]
https://github.com/cfpb/design-system/pull/1471 should go in first and then the config should be updated here.

**Comment by anselmbradford** [comment]
Fixes https://[GHE]/Design-Development/Design-and-Content-Team/issues/79

**Comment by anselmbradford** [comment]
The accessibility flagged issues should be addressed in a separate PR.

**Review by wpears — APPROVED** [review]

**Pull request merged**
