### PR TITLE
Tables: Adjust table header style

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Changes table headers from H5 to paragraph medium, sentence case, and top-aligning the baseline.

## Testing

1. Check tables page in this PR and compare table headers to https://cfpb.github.io/design-system/components/tables

## Screenshots

Before:
Screen Shot 2021-01-12 at 1 21 24 PM

After:
Screen Shot 2021-01-12 at 1 30 35 PM

### CODE REVIEW

**Comment by sonnakim** [comment]
Looks good to me @anselmbradford. So nice to say goodbye to all caps for the table headers. Only thing I notice is that [the request](https://github.com/cfpb/design-system/issues/1052) asks for a background color of #F8F8F8, which looks like it would be a change from the #f7f8f9 we usually use (https://www.consumerfinance.gov/consumer-tools/educator-tools/resources-for-older-adults/financial-security-as-you-age/),  I'm not sure if they're specifically asking to change the background color or if maybe they had the wrong spec listed?

**Comment by anselmbradford** [comment]
>  I'm not sure if they're specifically asking to change the background color or if maybe they had the wrong spec listed?

Yea I asked this in chat on makeathon day and my understanding is the f8f8f8 is incorrect in the issue.

**Comment by huetingj** [comment]
Yah, #F8F8F8 isn't in [our palette](https://cfpb.github.io/design-system/foundation/color). But I just noticed that we state #F8F8F8 in the design specs on the [Tables page](https://cfpb.github.io/design-system/components/tables). Aiy aiy. 

Keep it coded as #f7f8f9. I'll update the Tables DS page now to state #f7f8f9.

And I like the look of paragraph medium, sentence case, top-aligning the baseline!

**Comment by sonnakim** [comment]
Good catch @huetingj ! Thanks for making that update.

**Review by contolini — APPROVED** [review]
🚀

**Pull request merged**
