### PR TITLE
Update “info-unit-groups”

### PR DESCRIPTION
**Pull request by marteki**
Automatically generated by Netlify CMS

Edits in preparation for a new related page that will be created and called "Info Unit Groups: Link blobs"

### CODE REVIEW

**Comment by marteki** [comment]
Thanks, @cfarm. Things went wonky there.

Do you think I'm good to continue editing as is?

**Comment by cfarm** [comment]
are your content edits affected? can you be specific about wonky? 

if all is working please continue and i'll remove my commits from this branch when youre done, sorry about that.

**Comment by marteki** [comment]
@cfarm I don't think your commits broke anything at all, and thought that you were fixing something I didn't see on my behalf. We should be all good. If not, we'll figure it out later. 👍

**Comment by cfarm** [comment]
I fixed all the changes I had made to this branch, so @marteki you should be able to proceed as normal now! thanks for your patience.

**Comment by marteki** [comment]
Having issues saving changes to this branch due to that familiar API error (see the screenshot for reference). 

Screen Shot 2019-08-22 at 9 41 08 AM

I'll try to merge the existing content changes, then finish migration for this page later. @cfarm should I wait on anything you want to do for your commits before I do that?

**Pull request merged**
