### PR TITLE
Update “notifications”

### PR DESCRIPTION
**Pull request by marteki**
Automatically generated by Netlify CMS

(Continue work on [the Notifications page](https://cfpb.github.io/design-system/components/notifications), which was still in active progress two weeks ago)

### Currently deployed version

Screen Shot 2019-08-19 at 3 16 31 PM

Screen Shot 2019-08-19 at 3 16 53 PM

### Changes in this PR, to review

Screen Shot 2019-08-19 at 3 17 35 PM

Screen Shot 2019-08-19 at 3 17 44 PM

Screen Shot 2019-08-19 at 3 18 17 PM

### CODE REVIEW

**Comment by marteki** [comment]
@contolini Could you look into what's going on with the specfication tables on these pages? The default one is showing up at the very end of all the variations instead of inside the first one, and all the rest are offset by one to appear on the variation before the one they're supposed to.

Screenshot to show what's happening on the currently deployed site and this PR:
Screen Shot 2019-08-19 at 2 22 23 PM

**Comment by designlanguage** [comment]
@marteki - I wonder if that's related to the content shifting bug #280

**Comment by marteki** [comment]
@designlanguage Good point! Can you note it as possibly related on that issue?

**Comment by marteki** [comment]
>Should we include a basic form alert as a variation before we get to the examples of success/error, etc?

I don't think one exist? That would just be a standard form field and not an alert, right?

> Will the loading icon animate, or is the system not set up to support that currently?

:+1: Good idea. I grabbed the code from Capital Framework, which doesn't animate. I'll see if I can figure out what tag to use to get the Design Manual animated version.

**Comment by designlanguage** [comment]
Ah okay re: form alerts. This looks good to merge!

**Pull request merged**
